### ISSUE TITLE
Missed source code of 2 files

### ISSUE THREAD

**Issue by bkocherov** [ONLYOFFICE/DocumentServer#10]
2 binary files have no source code: 
ServerComponents/Bin/libdoctrenderer.so
ServerComponents/Bin/x2t

**Comment by AnaMih** [comment]
Yes, there is no source code for these two files, we don't open it.

**Comment by tsmgodoi** [comment]
@AnaMih 
Any news about publishing the missing source code for these files?
Thanks.

**Comment by ibnpetr** [comment]
@tsmgodoi 
No, the files aren't available yet. (I cannot specify the time frame)

**Comment by gridworkz** [comment]
It's nice to see you're planning to open source these files. They look pretty substantial. Are they proprietary? I'm just wondering why they're taking a bit to open source.
Cheers,
Dave

**Comment by cjdelisle** [comment]
+1 this, for those who don't know this is the heart of the converter which makes OnlyOffice able to read and write Word/Excel files.
@ibnpetr if the issue is technical (build system, etc) perhaps you can just dump the code in the repo and we can help you get it running as a community.

**Comment by gridworkz** [comment]
Hi Caleb:

Thanks for the interest. I'm available to dedicate my time to this. Let me
know exactly what you need and I'll see that it gets done. There are 2 main
files (x2t and libdoctrendere.so) that are core to the process. There is
also editor.bin which stores files in OnlyOffice format. x2t and
libdoctrender.so are quite substantial in size.

x2t: It converts all docx, xlsx, and pptx files to internal doct, xlst and
pptt format. (sometimes referred to as docy, xlsy and ppty in the code).
Did a quick readelf on it and it's a standard gcc_x64 elf binary.

libdoctrender.so: It's a little more interesting. It uses, among other
standard things, Google CEF (Chromium Embedded Framework), V8 and Qt5.
Probably Qt5 Webkit for V8. This file is the layout manager and doc
renderer for the browser. I suspect V8 talks directly to Javascript and
HTML5 canvas stuff.

Anyway, I'm thrilled that somebody, other than myself and a few other
people, are interested in pursuing this.

Cheers,
Dave

**Comment by cjdelisle** [comment]
Hi Dave,
That seems to be in agreement with what I discovered, although I was under the impression that it was converting between xlsx and xls (old format) too. Personally I would love to have the xlsx/xlst conversion code since that code would be a de-facto specification for the "Editor.bin" format. I did an strace of the thing to see what it was doing when it converted and it doesn't seem to do too much in the way of interacting with the system.

If I wanted to pursue it more, I might consider to do an execution trace of the types of conversion I want to do and then see about removing unnecessary code. From there I could imagine running it through a "translator" type disassembler and compile the resulting garbage pile of C into Javascript/WebAssembly in order that the webapp can export xls without server assistance.

However I'm not that motivated so I'll probably stick to running x2t in a sandboxed environment and make it a little web service until the developers decide if they're going to release source code.

Side note 1: The executable is not stripped, I wonder what you get running it in a debugger - at least the stack traces won't be horrible...
Side note 2: Seems to statically link a lot of libraries for dealing with png, tiff, jpeg etc, very likely this is exploitable using known exploits.

**Comment by polx** [comment]
It would be cool that the development goes more active in this project indeed.
E.g. elementary errors that can be found here and there would be certainly fixed by the community.
Dave, your description of the multiple layers seems quite impressive... If sorting out all the legalese is what's needed to open-source x2t, it might be long.
paul

**Comment by gridworkz** [comment]
Hi Paul:

Sorry for the late reply. Yes, I just forked DocumentServer and I'm going
to do some poking around. I'm willing to turn this into a project if anyone
else is interested. I'm just trying to figure out where to start. Caleb had
some great input.

Caleb was correct in that x2t also converts xls to xlsx. I'm willing to
stare at dtraces and such all day long if somebody can point me in the
right direction :-) I have a fair bit of spare time at the moment.

Cheers,
Dave

**Comment by gridworkz** [comment]
Do you guys have emails I can reach you at?
Cheers,
Dave

**Comment by gridworkz** [comment]
Hi Caleb:

A little more digging and I think the "editor.bin" file is in the format:
OpenMcdf compound file format for storage of file streams. It also works on
Mono so this further leads me to believe it's the one.

https://sourceforge.net/projects/openmcdf/?source=typ_redirect. They refer
to it quite a bit during conversion and file manpulations.

Cheers,
Dave

**Comment by cjdelisle** [comment]
Ahh interesting, if that's true then it's basically a .doc/.xls file.
I took a quick look at this file which is doing the actual serialization

https://github.com/xwiki-labs/SaoO/blob/master/OfficeWeb/sdk/Excel/model/Serialize.js#L7358

but at this point I don't have huge time available for researching this
particular topic, I'm working on trying to make OnlyOffice have realtime
editing similar to Google Docs.

If you want to contact me directly, you can email calebjamesdelisle at xwiki com
or all of us at research at xwiki com

Thanks,
Caleb

**Comment by gridworkz** [comment]
Hi Caleb:

Thanks for the info. Good luck with your project. I'll just keep you
updated if I find anything juicy to help you guys out.

Cheers,
Dave

**Comment by Dean13** [comment]
Thank you all for a discussion. We are close to release Open Source Version and those files will be there. Thank you for your patience, we will be glad to receive a response from you.

**Comment by gridworkz** [comment]
Hi Dean:

Thanks. Don't worry I won't ask you for a time frame, however, even
alpha/beta code would suit us just fine if we could get it now.

Cheers,
Dave

**Comment by trofim24** [comment]
We are release Open Source Version and those files:
https://github.com/ONLYOFFICE/core/tree/master/X2tConverter
https://github.com/ONLYOFFICE/core/tree/master/DesktopEditor/doctrenderer

Thank you for your patience.

**Comment by cjdelisle** [comment]
Excellent work and great code, thanks for going through with it to make this happen !

**Comment by gridworkz** [comment]
This is an amazing effort and a bit of a game changer in my mind....well
done.
Dave
