### ISSUE TITLE
Bad German Spell Checking

### ISSUE THREAD

**Issue by kojid0** [ONLYOFFICE/DocumentServer#1033]
**Do you want to request a *feature* or report a *bug*?**
I want to report a feature enhancement and a bug.

**What is the current behavior?**
Many words are underlined red (spell check) even though they are correct (German language). Sometimes, words get underlines with the improvement to replace it with the same word.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Examples of words that exist, but are underlined:

1. "Interaktionsgeräte"
2. "Klassenvariable"
3. "Attributwert"

Words where the improvement is the same word:

4. "Schlägt" (bug: it tells me to replace it with "Schlägt" (the same) but still underlining...)
5. "bzw." (abbreviation for "beziehungsweise") (bug: it tells me to replace it with "bzw." (the same) which adds another dot (still underlining)).
6. "Für" (bug: it tells me to replace it with "Für" (the same) but still underlining...)

**What is the expected behavior?**
Like in MS Office, 1+2+3 should not be underlined. Oddly they get underlined in my browser (Brave, based on Chromium) too, but not in MS Office.
There should be no improvement suggestion for 4+5+6.

**Which versions of DesktopEditors, and which OS are affected by this issue?**
Using onlyoffice 5.2.83480 on zorinOS (Ubuntu 18.04.2).

**Comment by ShockwaveNN** [comment]
Moving this issue to DocumentServer repo, since it's our base product and problem actual there too

**Comment by solarjoe** [comment]
Some other issues with German spell checking:

1.) 
I have the same issue (Desktop Editors Version 5.6.4.20) with German spell checking. Bold means underlined.

"**Softwareent**- und **abwicklung**" is highlighted, which points to an issue with hyphenation. 
It's a correct hyphenation and abbreviation. Instead of "Softwareentwickung und Softwareabwicklung" you can write
"Softwareent- und abwicklung". Save a "wicklung" :) . But you can also write "Softwareentwickung und -abwicklung", save-split at a different position. Basically you can choose how much to save and what sounds better :)

2.) 
"Es gibt mögliche Anwendungen ..." is detected correctly, but "**Mögliche** Anwendungen sind ..." is detected as incorrect. Could be an issue with context detection or capitalization. But I think it is also related to German "Umlaut" (ä, ü, ö).

**Comment by Rita-Bubnova** [comment]
> 1.)
I have the same issue (Desktop Editors Version 5.6.4.20) with German spell checking. Bold means underlined.
"Softwareent- und abwicklung" is highlighted, which points to an issue with hyphenation.
It's a correct hyphenation and abbreviation. Instead of "Softwareentwickung und Softwareabwicklung" you can write
"Softwareent- und abwicklung". Save a "wicklung" :) . But you can also write "Softwareentwickung und -abwicklung", save-split at a different position. Basically you can choose how much to save and what sounds better :)

Can you create completely new issue? In order not to mix your problem with the original problems in this release.

**Comment by solarjoe** [comment]
Done.

> Can you create completely new issue? In order not to mix your problem with the original problems in this issue.

Done. https://github.com/ONLYOFFICE/DocumentServer/issues/1037

**Comment by trofim24** [comment]
We fixed this problem and released Document Server version 6.3.0
@ShockwaveNN, will you close the issue after we will release Desktop Editors version 6.3.0?

**Comment by ShockwaveNN** [comment]
@trofim24 Yes, original issue was on DesktopEditors, so I'll close it as soon as we release DesktopEditors v6.3 (I hope soon)

**Comment by ShockwaveNN** [comment]
DocumentServer and DesktopEditors v6.3.1 is released. This issue should be fixed
