### ISSUE TITLE
Mobile Support

### ISSUE THREAD

**Issue by lemonbyte** [ONLYOFFICE/DocumentServer#115]
**General :**
- Wich mobile browsers are supported.
- Wich mobile device's are supported.
- Wich mobile OS are supported.

**Problem 1:** We having a problem when mobile version is loaded on Ipad. 
The keybord is displayed correctly but is not (always) working. The cursor in the document stays the same and is not registring any keybord strokes.

**Problem 2:**  When the document is loaded within the incognito mode in the browser it does not show the document content at al.

Document Server version is 4.3.3

**Comment by ayuzhin** [comment]
**General :**
Mobile Editors are supported by all browser on webkit engine. Which device or OS does not matter, the application works in the browser.

**Problem 1:** 
Unfortunately, it was not possible to reproduce the problem. Describe in more detail how we can reproduce it. Does the problem repeat on the public portal personal.onlyoffice.com?

**Problem 2:** 
The problem will be fixed in the next update.

**Comment by ShockwaveNN** [comment]
This issues should not be actual any more, if not - please open new issue
