### ISSUE TITLE
How to compile Docs for Windows 10?

### ISSUE THREAD

**Issue by DUOLabs333** [ONLYOFFICE/DocumentServer#1154]
I know that there is an .exe file to install it, but I like to make my software as portable as possible (and not write to the registry), so I'm interested in compiling Docs from the source in a pre-set folder. Is there a way to do that (for example, how are the .exe's generated)?

**Comment by ShockwaveNN** [comment]
Hi, currently we got no working instruction for compiling on Windows, but our dev team are working on it

There is already an issue about this: https://github.com/ONLYOFFICE/build_tools/issues/105
It's for DesktopEditors, but this apply to DocumentServer also, since our build process depends one on another

I'll close this issue and you should monitor build_tools#105 for any progress
