### ISSUE TITLE
Hope to have a function, convert doc to HTML

### ISSUE THREAD

**Issue by hbpbpl** [ONLYOFFICE/DocumentServer#1170]
Featrue/Enhancement
**ConvertService**  Conversion from doc to HTML is not supported

**Comment by ShockwaveNN** [comment]
Hi there, I've just checked and we're implemented convert document files to HTML/fb2/epub in future version of DocumentServer 6.3

I've checked on current dev build 6.3.0.46 and didn't find any critical error on small list of files

But I cannot guarantee any time-frame of v6.3 release, because currently it's not fully tested

**Comment by ShockwaveNN** [comment]
DocumentServer v6.3.0 is released. This problem should be fixed
