### ISSUE TITLE
Avoid asking user to clear cache when adding a font

### ISSUE THREAD

**Issue by pierreozoux** [ONLYOFFICE/DocumentServer#1238]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently when you follow [this doc](https://helpcenter.onlyoffice.com/en/installation/docs-community-install-fonts-linux.aspx) it is asked for the end user to clear cache to see the newly installed font.

As an end user, that is not necessarily familiar with technology, this would be a difficult operation.

It would be nice if the cache clearing wouldn't be necessary on the user side.

**Comment by ShockwaveNN** [comment]
Hi there, thanks for your idea

I agree this is not a good way to handle user situation, but as far as I remember there was troubles implementing auto-clean cache mechanism

We're long aware of this problem, but I think we never formally fixated it and problem related to fixing it, so I've create issue 49811 in our private issue tracker

I will not promise that this problem will resolve soon, since I'm not quite remember troubles we got last time several years ago, but if there be any news - I post it here

**Comment by ShockwaveNN** [comment]
Seems I missed - we got an earlier same issue

https://github.com/ONLYOFFICE/DocumentServer/issues/329, making 329 primal one and closing this
