### ISSUE TITLE
Not able to edit a file, document can not be saved warning, download failed error 

### ISSUE THREAD

**Issue by Ariel505** [ONLYOFFICE/DocumentServer#1345]
**Do you want to request a *feature* or report a *bug*?**
bug, maybe in local virtual machine configuration

**What is the current behavior?**
The onlyoffice document Edit view in Humhub is not able to load the file

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
https://cloud.hcu-hamburg.de/nextcloud/s/3DooZToxFMjY4eD
- See the screenshot recording 

**What is the expected behavior?**
Multiple user shall be able to edit the file.

**Did this work in previous versions of DocumentServer?**
Document server is hosting on https://sure.hcu-hamburg.de
Humhub is hosting on https://humhub.sure.hcu-hamburg.de

**DocumentServer version:**
6.3.1.32

**Operating System:**
Ubuntu 18.04.02 LTS

**Browser version:**
Firefox / Chrome

When I was testing onlyoffice with official example instruction:
https://sure.hcu-hamburg.de/welcome/
I am able to create a file and edit it, however, other user has no access to the same file, is there somewhere I have to configure?

Onlyoffice were installed without docker but follow this instructions:
https://helpcenter.onlyoffice.com/installation/docs-community-install-ubuntu.aspx

Any suggestion will be greatful, for I find no clue from Humhub logs.

**Comment by Ariel505** [comment]
The Humhub pre-request check
![pre_request](https://user-images.githubusercontent.com/37367728/126329122-a017bbcd-14d0-478e-89b6-bf39bb222a2f.PNG)

**Comment by ShockwaveNN** [comment]
>  When I was testing onlyoffice with official example instruction:
> https://sure.hcu-hamburg.de/welcome/
> I am able to create a file and edit it, however, other user has no access to the same file, is there somewhere I have to configure?

This is correct behavior since https://sure.hcu-hamburg.de/example/ use IP's to store edited files and since two users have different IP's - they cannod edit same file

I see myself that DocumentServer by itself seems working fine, so problem probably on HumHub side

Judging by your video - DocumentServer cannot access files hosted on HumHub side, maybe you can find some 5xx or 4xx errors in DocumentServer logs. Maybe some firewall blocking it

Generally speaking HubHub integration extensions is not develop by ONLYOFFICE team so you should contact HumHub extension support

**Comment by Ariel505** [comment]
Thanks ShockwaveNN this is very helpful.

Best,
Ariel
