### ISSUE TITLE
What is the maximum size of Excel and Word files supported and recommended in the product?

### ISSUE THREAD

**Issue by ChupakabraMSK** [ONLYOFFICE/DocumentServer#1391]
What is the maximum size of Excel and Word files supported and recommended in the product?

**Comment by ShockwaveNN** [comment]
You cannot measure complexity of those file just by size

Because you can create 2mb xlsx file - one line of text and 1.99MB image in this file
And you can create 2mb xlsx file - 200mb repeated string data, effectively archived in 2mb file and this is a lot more CPU and memory intensive than 1 case

Judging by our practice - files around 100-150MB can be opened effectively, but it's depends of its' content

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
