### ISSUE TITLE
can't use pagespeed to test web performance

### ISSUE THREAD

**Issue by Malenconiaprincep** [ONLYOFFICE/DocumentServer#1465]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**

The reason was that I wanted to analyze the performance of the onlyOffice page, and I found that this URL was used in Pagespeed Insight. the url is [https://personal.onlyoffice.com/Products/Files/DocEditor.aspx?fileid=4311060&doc=eTY1Vm1FU2R2czI1OFJ4QlBvMnhjQS9IbFJDMXo0UFArTS8zUUpLZ29OST0_IjQzMTEwNjAi0](url)

The test web performance tool's url is [https://developers.google.com/speed/pagespeed/insights/](url)

It cause some errors that Lighthouse returned error: NO_FCP.  The page does not render anything. Be sure to keep the browser window in the foreground during web page loading, and then try again.

**Comment by ShockwaveNN** [comment]
Yeah, I see the same error as yours 

![image](https://user-images.githubusercontent.com/668524/137117362-6e8edfb3-0214-4081-b25b-6aad8a3caffb.png)

I think it's a limitation of PageSpeed - our personal page insert iframe with an instance of DocumentServer inside page URL you've mentioned and seems PageSpeed does not like this

I've never used this tool, but maybe there is some disclaimer about limitations in documentation?
But in any case - I don't think it's issue on our side and you should contact PageSpeed developers, but I do not think it may result any positive outcome, since I've heard Google does not have a greater support

**Comment by Malenconiaprincep** [comment]
Oh, I see. By the way, what tools do you use to test web performance?
