### ISSUE TITLE
No support of psql `scram-sha-256` auth method

### ISSUE THREAD

**Issue by DKiyanov** [ONLYOFFICE/DocumentServer#1537]
Проблема с установкой Community Edition 
по всей видимости не совместимость с 13 - 14 версиями postgresql

Проявлялась зависанием при создании документа

в логе установки нашёл:
2021-12-04 14:41:28.021   Run as: Current user
2021-12-04 14:41:28.021   Type: Exec
2021-12-04 14:41:28.021   Filename: C:\Program Files\ONLYOFFICE\DocumentServer\pgsql\bin\psql.exe
2021-12-04 14:41:28.021   Parameters: -h localhost -U onlyoffice -d onlyoffice -w -q -f "C:\Program Files\ONLYOFFICE\DocumentServer\server\schema\postgresql\removetbl.sql"
2021-12-04 14:41:28.115   Process exit code: 2
2021-12-04 14:41:28.115   -- Run entry --
2021-12-04 14:41:28.115   Run as: Current user
2021-12-04 14:41:28.115   Type: Exec
2021-12-04 14:41:28.115   Filename: C:\Program Files\ONLYOFFICE\DocumentServer\pgsql\bin\psql.exe
2021-12-04 14:41:28.115   Parameters: -h localhost -U onlyoffice -d onlyoffice -w -q -f "C:\Program Files\ONLYOFFICE\DocumentServer\server\schema\postgresql\createdb.sql"
2021-12-04 14:41:28.208   Process exit code: 2

повторение команды в ручную выдало:
psql: authentication method 10 not supported

вылечил:
C:\Program Files\PostgreSQL\13\data\pg_hba.conf.
local all all trust
host all all 127.0.0.1/32 trust
host all all ::1/128 trust

**Comment by ShockwaveNN** [comment]
Hi, please do not use only Russian language in issues

We only allow English in messages, you can duplicate your message in Russian, but this message should be readable for anyone since this tracker is public and so English is the only allowed language.

-------
Пожалуйста, не используйте только русский язык в issues. Заголовок и большая часть тела должна быть на английском. Но можете продублировать сообщение более детально на русском.
Если вас это не устраивает - попробуйте обратиться в support@onlyoffice.com - там общаются на разных языках

**Comment by ShockwaveNN** [comment]
And about issue itelf - @igwyd please, take a look as soon as you got free time, I'm almost sure that linux version of psql has no troubles with auth, but  seems we may provide very old version of `psql` bundled with Windows installation

**Comment by igwyd** [comment]
Hello @DKiyanov, by default postgresql since 13 version using scram-sha-256 encryption method, the documentserver does not support it method at the installation phase, we have a bug 49168 on our private issue tracker.
But the documentserver can work with scram-sha-256, we have workaround:
* Install PostgreSQL 13 or 14, change the encryption method to md5 in pg_hba.conf and postgresql.conf, restart postgre service
* Create a user and databases then install onlyoffice-documentserver.
* Change password encryption method in postgre - password_encryption = scram-sha-256 in postgresql.conf and restart postgre service
* Change the password of the onlyoffice user to the same one that was set during creation (the password will be encrypted in scram-sha-256)
* Establish connection in pg_hba.conf on scram-sha-256 and restart postgre service

**Comment by igwyd** [comment]
It's fixed at:
https://github.com/ONLYOFFICE/document-server-package/commit/6329b3ac1df3955c5336adfe07b00ce495acfb41
and was released from version 7.0.0

**Comment by dwpoint** [comment]
@igwyd Hello! I'm using the new version of WorkSpace, but I'm having the same problem connecting to PostrgeSQL. What can you try to do? Scram-sha-256 is already there
PostgreSQL version 14 is used

**Comment by dwpoint** [comment]
@ShockwaveNN im using x86

**Comment by igwyd** [comment]
Hello @dwpoint, please describe the scenario in more detail so that we can check it and recommend a solution. Also provide the server operating system and ONLYOFFICE document server version.

**Comment by dwpoint** [comment]
@igwyd Everything is super! Settled!
Tell me, is it possible to disable the mail module completely in WorkSpace? So that no confirmations through the mail come and notifications too. I have WorkSpace on a closed network. I would like OnlyOffice to have no access to the Internet at all. Is it possible?

**Comment by igwyd** [comment]
@dwpoint this question is not appropriate for this issue, you should look for the answer in [CommunityServer repository](https://github.com/ONLYOFFICE/CommunityServer) and if you don't find it, create a new issue.
