### ISSUE TITLE
Invalid custom settings logo object

### ISSUE THREAD

**Issue by bszhct** [ONLYOFFICE/DocumentServer#1550]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Invalid custom settings logo object

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I configured the logo field:

```js
customization: {
  logo: {
    image: 'http://IP:3301/static/logo.png',
    imageEmbedded: 'http://IP:3301/static/logo.png',
    url: 'http://www.example.com'
  }
}

```

But it only takes effect when the page is initialized, and after the page is loaded, it becomes the default logo again.

![image](https://user-images.githubusercontent.com/56250514/145800461-dc335910-f682-4762-9708-dc20ceaf2561.png)

![image](https://user-images.githubusercontent.com/56250514/145800498-e483d2e7-aa8f-4ca3-add5-c1a6654c5c07.png)

**What is the expected behavior?**
Logo settings can take effect permanently

**Did this work in previous versions of DocumentServer?**
have no idea

**DocumentServer version:**
6.4.2

**Operating System:**
macOS Mojave 10.14.5

**Browser version:**
Chrome 96.0.46xxx

**Comment by ShockwaveNN** [comment]
@igwyd Please, take a look as soon as you got free time

**Comment by igwyd** [comment]
Hello @bszhct, i think the logo disappears because you used the Onlyoffice-Documentserver Community Edition. [Here](https://api.onlyoffice.com/editors/config/editor/customization#logo) our api documentation, logo settings with star and below is a footnote "* - available for editing only for ONLYOFFICE Developer Edition". Try to use Onlyoffice-Documentserver Developer Edition, for example in docker [onlyoffice/documentserver-de](https://hub.docker.com/r/onlyoffice/documentserver-de/tags?page=1&ordering=last_updated)

**Comment by bszhct** [comment]
OK, thanks~

**Comment by ShockwaveNN** [comment]
In that case I'll close this issue, but feel free to comment or create a new one if any questions
