### ISSUE TITLE
when set type = mobile , no avail in Android

### ISSUE THREAD

**Issue by kaizi000** [ONLYOFFICE/DocumentServer#1602]
version  6.3.0；
![image](https://user-images.githubusercontent.com/22171155/150775296-7752741a-32d3-4b5b-85af-8fa444108edc.png)
![image](https://user-images.githubusercontent.com/22171155/150775393-0a0c5594-4337-4a67-92d7-36b10b4ccdcb.png)

**Comment by kaizi000** [comment]
2、how to auto jump to page 2 when file type is docx ？

**Comment by ShockwaveNN** [comment]
Hi, please fill out issue template correctly

I cannot understand at all what you mean, please attach host os, screenshots error descriptions

Also v6.3.0 is rather old

And please note that mobile editors is not available on free package, as described here

https://github.com/ONLYOFFICE/DocumentServer#onlyoffice-document-server-editions

**Comment by kaizi000** [comment]
> descriptions
please see the picture above。we cannot upgrade latest version due to historical reasons。

**Comment by kaizi000** [comment]
when I want to open a document, I automatically jump to the specified number of pages。how to realize it，i didn't find the appropriate settings

**Comment by ShockwaveNN** [comment]
> we cannot upgrade latest version due to historical reasons。

Could you check if this issue persists on latest version of DocumentServer (setup it on other host)

We do not support older version and even if there is a bug already fixed in v7.0.0 - you have nothing to do except to upgrade

> I automatically jump to the specified number of pages。how to realize it，i didn't find the appropriate settings

I never heard of a similar situation. Is this happen to any file or some specific ones? We do not reopen file with position of older ropen.

So same here - recheck it with latest version
