### ISSUE TITLE
How to develop mode startup projects and debug code

### ISSUE THREAD

**Issue by hehos** [ONLYOFFICE/DocumentServer#1704]
I need to debug the code inside, mainly the server code.

How do I start the project in development mode? And you can debug your code.

**Comment by ShockwaveNN** [comment]
Hi, I think there is no guide for that, you cannot start whole application in development mode, because it consists of several submodules, each of one is on different language\framework

Most of [server](https://github.com/ONLYOFFICE/server) code is `nodejs` code, so you should debug it like any other nodejs application

Some parts (like [x2t](https://github.com/ONLYOFFICE/core), which convert files) is on C++, so any c++ debugger will go, but I think it's more complicated

And frontend part should be debugged via Chrome Debug tool or other browser debugger

**Comment by hehos** [comment]
> Hi, I think there is no guide for that, you cannot start whole application in development mode, because it consists of several submodules, each of one is on different language\framework
> 
> Most of [server](https://github.com/ONLYOFFICE/server) code is `nodejs` code, so you should debug it like any other nodejs application
> 
> Some parts (like [x2t](https://github.com/ONLYOFFICE/core), which convert files) is on C++, so any c++ debugger will go, but I think it's more complicated
> 
> And frontend part should be debugged via Chrome Debug tool or other browser debugger

It is better to have a document, how to start several services, how to coordinate. In this way, we can quickly understand the project.

**Comment by ShockwaveNN** [comment]
> It is better to have a document, how to start several services step by step

We got such document [here](https://github.com/ONLYOFFICE/build_tools)
There is a detailed guide on how to setup a working environment from source code

**Comment by hehos** [comment]
I just want to start the server, the core, SDKJS, web apps that several modules. - https://github.com/ONLYOFFICE/build_tools document too complex。

**Comment by hehos** [comment]
> > It is better to have a document, how to start several services step by step
> 
> We got such document [here](https://github.com/ONLYOFFICE/build_tools) There is a detailed guide on how to setup a working environment from source code

I just want to start the server, the core, SDKJS, web apps that several modules. - https://github.com/ONLYOFFICE/build_tools document too complex。

**Comment by ShockwaveNN** [comment]
It is complex because our app is complex :man_shrugging:

**Comment by hehos** [comment]
Through this document (https://helpcenter.onlyoffice.com/installation/docs-community-compile.aspx), I compiled no compiles all day today!

My requirement is to compile the core project and then have the Server project use the Core project

I have a few questions about my needs:
1. I don't need to use the desktop editor, so I don't need to use QT? Qt takes too long to compile!
2, I don't need so much dependence, right?<img width="664" alt="image" src="https://user-images.githubusercontent.com/8369919/164217850-e9cf9eeb-c169-4421-9c16-d541baf0afec.png">

This project relies on too many third-party libraries. It is recommended to compile and run each project and write separate documents for each project.

**Comment by ShockwaveNN** [comment]
> I don't need to use the desktop editor, so I don't need to use QT? Qt takes too long to compile!

You're right but right now we do not have proper guide how to do that, so you'll need to figure out it yourself. 
I agree, qt compiling is quite long, but it's only need to be done once

> , I don't need so much dependence, right?

I think all dependencies except QT is required for DocumentServer

> It is recommended to compile and run each project and write separate documents for each project.

As I said earlier - this is not an easy project to debug and I agree with you, but it's done how it's done because developers decided that it'll be easier

**Comment by hehos** [comment]
How do you get core projects to compile and run without qt dependencies

**Comment by ShockwaveNN** [comment]
> How do you get core projects to compile and run without qt dependencies?

Sorry, I do not know how to do that, you're on your own in this task

> Can you help me explain the steps in a little more detail?

I do not know steps in details, only advice - to read python code used to build that

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.

**Comment by zhaoxuanHome** [comment]
ONLYOFFICE/core模块 使用QT或者C++编辑软件进行调试代码？

**Comment by zhaoxuanHome** [comment]
你们在研发core模块时怎么进行调试运行的呢？

**Comment by trofim24** [comment]
@zhaoxuanHome please, write on English. And create new issue if you have any questions or problems
