### ISSUE TITLE
Ability to add custom save button

### ISSUE THREAD

**Issue by zkPMP** [ONLYOFFICE/DocumentServer#1750]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
I'm using the forced save function. Can I get the save event? For example, an external JavaScript button has the same function as saving

V：7.1.0

**Comment by ShockwaveNN** [comment]
Hi, could you clarify that's the end goal for you here?

Yout want to have a separate button on page in which DocumentServer is integrated?

**Comment by zkPMP** [comment]
Yes!

![image](https://user-images.githubusercontent.com/88358252/168935022-f673e7ad-551a-498c-847f-c4be9891c439.png)

This is my page.

I want the external save button to have the same function as the Save button in DocumentServer.

**Comment by zkPMP** [comment]
How can the external save button have the same save function as the Save button in DocumentServer？

**Comment by ShockwaveNN** [comment]
I've checked with our developers and currently there is no way to do that
I've create issue 57208 with discussion about it in our private issue tracker

I don't think we'll implement it really soon, so if you really need this feature - better contact sales@onlyoffice.com

**Comment by zkPMP** [comment]
ok，tks

**Comment by ShockwaveNN** [comment]
Actually we dig a little more - do you tried this method?

https://api.onlyoffice.com/editors/command/forcesave

**Comment by zkPMP** [comment]
I'm using the forced save function. 
My goal is to get the saved file path.
Java document save example in callback handler
https://api.onlyoffice.com/editors/callback#java
can get the path

His premise is to trigger by clicking save

**Comment by ShockwaveNN** [comment]
> get the saved file path.

But this data is handled via DMS\Integration not via DocumentServer, so I may be wrong, but it's up to you to implement this in your own DMS\Integration

DocumentServer do not know path to file, it's only using the key

**Comment by zkPMP** [comment]
tks
i am trying other wayes

**Comment by lorenzoale** [comment]
Hello, I have a similar problem, and the problem for me is that onlyoffice is contained in another page where there are fields that can be modified and all modifications (inside and outside the editor) should be saved at the same time. 
I alredy did the necessary to "simulate" the forcesave, and so my external button is working. The problem now is that I can't hide the save button, only disable it. And so, just to make things look nicer, I would like to know if there is any possibility to "catch" the "forceSave event" (i mean it would be nice to have a force save event in order to be able to catch in javascript when the user clicke in the docEditor forcesave button). I know I could do some tricks to catch it inside the callback fc implementation, but I don't like that idea too much. Do you think it would be possible to have something like that? Many thanks in advance, Alejandra

**Comment by RumbleWx** [comment]
click the button, and postMessage to the pulgin in the oo, then exec the Api.Save commond

**Comment by RumbleWx** [comment]
click the button, and postMessage to the pulgin in the oo, then exec the Api.Save commond by the event listener 'onExternalPluginMessage'

**Comment by YuanZhencai** [comment]
> click the button, and postMessage to the pulgin in the oo, then exec the Api.Save commond by the event listener 'onExternalPluginMessage'

Is there a demo?
