### ISSUE TITLE
In spreadsheet paste values only on filtered cells 

### ISSUE THREAD

**Issue by jpberdejo** [ONLYOFFICE/DocumentServer#1754]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my idea.

### Your idea.

When a filter is applied to a spreadsheet, copying and pasting a value replaces all cells hidden by the filter and only the displayed cells should be replaced.

**Comment by ShockwaveNN** [comment]
v7.1 has been released and this problem should be fixed

**Comment by VladimirProkofiev52** [comment]
Hello! @corareg 
I see that the issue described above has been marked as fixed. 
If you're encountering a similar problem, please create a separate Issue with a detailed description, including the version of your editor, and we'll do our best to assist you. 
If applicable, attach the file (if the issue is specific to it) or a screen recording demonstrating the problem.
