### ISSUE TITLE
refreshHistory arguments

### ISSUE THREAD

**Issue by new-ranger** [ONLYOFFICE/DocumentServer#1778]
I am working on 'Version history'. When I save the document, getting history object with serverVersion and changes properties. In OnRequestHistory function there are two arguments we have to pass to refreshHistory 1. currentVersion and 2. version. what are these two values? where I can get this?

**Comment by ShockwaveNN** [comment]
Hi, I'm not 100% sure but I think

`version` is numerical value of different version stored for this document, going from 1 up
`currecntVersion` is current version of document, since if you got for example 5 version, but your current version can be 3 if you comparing 3rd version

I'm not sure if I can explain this right, but I think the easiest way will be to setup `nodejs` test example (most feature full) in debu g mode and click several button and see for those values

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
