### ISSUE TITLE
google sheets doesn't display cell borders saved with onlyoffice

### ISSUE THREAD

**Issue by adrianinsaval** [ONLYOFFICE/DocumentServer#1842]
![image](https://user-images.githubusercontent.com/36372335/181345809-fc8c69d9-4319-4b29-b8d5-1b563d213cf5.png)

I would think this somewhat of a bug in google sheets since it displays properly in excel but there's evidently something different in how onlyoffice saves the borders since there is no issue gsheet displaying borders saved in excel or libreoffice, see the attached picture.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
[test.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/9202660/test.xlsx)
upload this file to a google drive folder then open that document on google's web editor, the second set of cells with borders is not displayed, these were created in onlyoffice.

**What is the expected behavior?**
the cell border data saved by onlyoffice shouldn't be any different from what excel or libreoffice save

**Did this work in previous versions of DocumentServer?**
not that I know of

**DocumentServer version:**
7.1.1

**Operating System:**
windows 10, same on linux since this is browser based

**Browser version:**
Brave browser version 1.41.100 Chromium: 103.0.5060.134

**Comment by ShockwaveNN** [comment]
Sorry to hear that, but I think if same document rendered OK in LibreOffice and MS Office - this mean that we done doc according to standard (since we try to maintain highest possible compatibility with MS Office, but not with google docs)

And this issue should be reported to Google Docs support (if there is any kind of support)

**Comment by adrianinsaval** [comment]
I understand that but IMO it's in your interest to have generally good compatibility, why is onlyoffice doing it different from MS office or even libreoffice?

**Comment by ShockwaveNN** [comment]
@adrianinsaval I see your point, but there are a lot of different options in the `ooxml` standard and if we did something not according to this standard - we are gladly happy to fix that

But right now seems that we need to add some workaround in our code because Google does not want to acknowledge its bug (or at least comment somehow), so I'm not sure that we should waste a lot of time trying to found out which option Google Docs doesn't like if this option is ok for any other editors

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
