### ISSUE TITLE
Delete multiple rows/columns in spreadsheet not working

### ISSUE THREAD

**Issue by Xyz00777** [ONLYOFFICE/DocumentServer#1867]
**Do you want to request a *feature* or report a *bug*?**
Bug/feature?

**What is the current behavior?**
Nothing happens if you try to delete multiple column or rows at same time (marked multiple columns or rows)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open a Spreadsheet. mark multiple column or row and try to delete them.
**What is the expected behavior?**

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**
ONLYOFFICE Desktop Editors version 5.4.2.30 (windows 10 Pro 1909) i dont have other platforms to check if there happens nothing too

**Comment by HectorB-2020** [comment]
@ShockwaveNN, @Rita-Bubnova, I'm afraid I cannot agree this has been fixed.
Please see my example with randomly selected rows. `Delete` drops only the last selected row.

Tested on v7.1.1.57, Windows 10.

**Comment by ShockwaveNN** [comment]
> Tested on v7.1.1.57, Windows 10

This is not fixed in v7.1.1 and will be fixed in next major release (probably it will be 7.2)

**Comment by ShockwaveNN** [comment]
DocumentServer v7.2 is released. This issue should be fixed

Feel free to comment or reopen it if you got further questions

**Comment by hubergitgif** [comment]
Hola, I still have this problem. I don't think it is fixed?

**Comment by VladimirProkofiev52** [comment]
Hello! @hubergitgif I have reviewed your issue but was not able to reproduce it in the current versions of the editor. According to our information, the issue should have been fixed in version 7.2.0 and all later versions.

If you are using an older version, please update to the latest version (9.4.0).

If the problem still occurs after updating, please create a separate issue with a detailed description and steps to reproduce it.
