### ISSUE TITLE
Too Easy Lose Connection, how to custom the timeout config?

### ISSUE THREAD

**Issue by chunpu** [ONLYOFFICE/DocumentServer#1909]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**

1. Close wifi in my windows PC
2. several minutes after
3. reopen wifi
4. it has lost connection, all I can do is refresh page

![image](https://user-images.githubusercontent.com/4565306/190850970-69cf7e7e-1667-4e28-a855-f890bd2f89ff.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

--

**What is the expected behavior?**

Hope developper can control the connection timeout config.

Is there something in `default.json` config can control connection timeout?

**Did this work in previous versions of DocumentServer?**

no

**DocumentServer version:**
7.1.1

**Operating System:**
windows

**Browser version:**
105.0.5195.125

**Comment by ShockwaveNN** [comment]
I don't think we got any option to specify this timeout

We showing this message because in our engine lost of connection can cause lost of data in some very complicated scenarios in coedit mode so we got a hard chose

1. Do not show any message but allow user to lost data in some rare cases
2. Show this message but data lost never happens

So we chosen second option because user data is most important thing

So I don't think there anything to be done here

**Comment by chunpu** [comment]
Thanks for reply!

So can I choose to close the coedit mode?

because in some case user just need online single person edit, not coedit mode.

maybe in one user mode no data will lose.

**Comment by ShockwaveNN** [comment]
> So can I choose to close the coedit mode?

No, sorry, it's essential part of our engine and it's not optional

**Comment by trofim24** [comment]
we've changed our behavior for this
if file version doesn't change, we reconnect and continue working
please, check it on version 7.4.1 and create new issue if you have any questions
