### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by Chiyy** [ONLYOFFICE/DocumentServer#2012]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Windows Server

### Version information

7.2.1

### Expected Behavior

web-apps/apps/spreadsheeteditor/main/locale/zh.json
line 565:"SSE.Controllers.Main.txtPages": "页面",

### Actual Behavior

web-apps/apps/spreadsheeteditor/main/locale/zh.json
line 565:"SSE.Controllers.Main.txtPages": "页数",

**Comment by trofim24** [comment]
Hi.
web-apps/apps/spreadsheeteditor/main/locale/zh.json
[line 565](https://github.com/ONLYOFFICE/web-apps/blob/master/apps/spreadsheeteditor/main/locale/zh.json#L565) contains `"SSE.Controllers.DocumentHolder.txtEqualsToFontColor": "等于字体颜色",`

And if we search `"SSE.Controllers.Main.txtPages": "页面",` we will find it on [line 888](https://github.com/ONLYOFFICE/web-apps/blob/master/apps/spreadsheeteditor/main/locale/zh.json#L888). It equals to your "Expected Behavior"

so please explain what you mean or maybe it's already fixed

**Comment by Chiyy** [comment]
❌"SSE.Controllers.Main.txtPages": "页面"
✔"SSE.Controllers.Main.txtPages": "页数"

**Comment by trofim24** [comment]
[fixed](https://github.com/ONLYOFFICE/web-apps/pull/2568)

**Comment by Rita-Bubnova** [comment]
DocumentServer v7.5.0 is released so I close this issue. Feel free to comment or reopen it if you got further questions.
