### ISSUE TITLE
No Makefile to compile

### ISSUE THREAD

**Issue by FabianoK** [ONLYOFFICE/DocumentServer#21]
I'm followed the steps in http://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx and when I try compile I get the message no make file found. OS: Debian Jessie 64

**Comment by ibnpetr** [comment]
Hello
Thanks for the info
The instructions have been updated
Please follow them once again

**Comment by gridworkz** [comment]
I too get the same message - are the docs updated?
Cheers,
Dave

**Comment by ibnpetr** [comment]
Hi Dave
Specify the OS and kernel

**Comment by gridworkz** [comment]
Hi:
Kernel: 3.13.0-74-generic 
OS: Ubuntu 14.04.3 LTS (Trusty). 
Amazon EC2 instance (Small -> 2Gb RAM -1 vCPU)
But...
the current docs at ,http://helpcenter.onlyoffice.com/server/linux/document/compile-source-code.aspx don't match the DocumentServer Github repo. The steps to launch DocService and FileConverter Service don't work because ../NodeJsProjects/FileConverter/sources/convertermaster.js and  ../NodeJsProjects/DocService/sources/server.js don't exist in the repo. Spellchecker does launch.

I tried to build with: _xbuild DocumentServer/build/projects/build.proj_ (which I think worked) but there is no Make file as per the documentation. I've allocated my time directly to this project so if you need me to do anything to help / test please feel free to let me know.

Cheers,
Dave

**Comment by trofim24** [comment]
fix with new version
Use the installation instructions [Installing ONLYOFFICE Document Server Linux Version](http://helpcenter.onlyoffice.com/ru/server/linux/document/linux-installation.aspx)
