### ISSUE TITLE
"Delete style" works as intended?

### ISSUE THREAD

**Issue by Julvenzor** [ONLYOFFICE/DocumentServer#2145]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocuemntServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (DEB package)

### Version information

7.3

### Expected Behavior

In the word processor, to the left of the style application, there is a button to delete the style of the text ("delete style"). According to the documentation and its equivalent in other word processors, that button should remove direct formatting, ie bolding, italics, underlining, and any changes that are not set to paragraph style.

### Actual Behavior

However, when the user clicks the button that is not what happens. OnlyOffice's word processor deletes styles and makes all selected text "normal". This literally causes all the text that was previously set as heading 1, 2, 3, etc., to lose its heading setting. I don't think this function is desired.

"Delete style" should remove all direct format, but never change the text from "heading 1" style to "normal" style. At the very least, I think there should be two different buttons or a dropdown menu where you can select whether to also clear the styling assignment for the selected text.

Regards.

### Reproduction Steps

1. Write some text and set it as "heading 1" or others.
2. Select some characters and apply bold, italics, and others.
3. Select the text and click the "delete style" button.
4. All selected text becomes "normal" instead of just losing its direct format.

### Additional information

It also happens in previous versions.

**Comment by TatianaKirillova** [comment]
Hello, @Julvenzor
Thanks for your request!
By "delete style" did you mean the "clear style" button?
It looks like you selected only the word without the paragraph sign, and then applied the style to it.  In this situation, Heading1-9 styles are applied directly to the text, not to the paragraph. That's why "clear style" removed all the style you selected.
To apply Heading1-9 to a paragraph as a paragraph style you must select paragraph sign or place the cursor without any selection in the current paragraph.

**Comment by DenisDeeSign** [comment]
This issue was closed due to no response.
