### ISSUE TITLE
 Are AGPL and CLA compatible? What about GDPR too?

### ISSUE THREAD

**Issue by Thatoo** [ONLYOFFICE/DocumentServer#2288]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

I see that onlyoffice promotes the Apache and AGPL licences: https://github.com/ONLYOFFICE/DocumentServer/blob/master/LICENSE.txt and https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/master/LICENSE
I see that signing a CLA is required from contributors: https://cla-assistant.io/ONLYOFFICE/onlyoffice-nextcloud?pullRequest=255
I'm having difficulty seeing the link between the two. Could you explain to me how AGPL is compatible with this CLA?

Furthermore, in Europe, we have the application of the GDPR (https://gdpr-info.eu/) and it is explained that the default choice must be to refuse to share data and that consent must be able to be withdrawn (https://gdpr-info.eu/art-7-gdpr/). I see a risk of incompatibility between the GDPR and the CLA, which could have a significant impact on contribution to OnlyOffice in Europe and block a situation where a contributor would not accept to sign such CLA.

Finally, I, personally, don't feel good about CLAs that require giving more rights to one party than another and this could be a reason for me to choose and promote other project that respects more its contributor's right.

**Comment by galegod06** [comment]
The purpose of the CLA is to ensure that the project and its users do not face legal problems related to intellectual property rights in the future, as the agreement proposes to pre-clear agreements on the rights to distribute, license and sublicense the provided code.

So, the AGPL and the CLA are compatible because the AGPL is mainly about the distribution and availability of source code, while the CLA focuses on granting rights to project maintainers. Essentially, by signing the CLA, contributors allow maintainers to distribute their contributions under the terms of the chosen license.

ONLYOFFICE, through the use of the AGPL license, guarantees the availability of the source code, and the CLA allows project maintainers to distribute the code in accordance with the selected license terms.

Regarding concerns about the General Data Protection Regulation (GDPR) - the GDPR emphasizes the importance of user consent and the ability to withdraw consent when it comes to data sharing and we are committed to these obligations.

It's important to note that the CLA is not about sharing personal data, but rather about code's contribution to the project. CLA guarantees that the project can distribute the provided code in accordance with the chosen license, and not that personal data will be transferred without consent.
