### ISSUE TITLE
Add user filter to the spreadsheet editor

### ISSUE THREAD

**Issue by ostasevych** [ONLYOFFICE/DocumentServer#2297]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

The OnlyOffice spreadsheet editor allows to have automatic and custom filters to filter the data shown to users. When a user applies some filter to a shared document all other users becomes affected, so they see the filtered document.

I suggest to add the user filter which settings are saved on per-user level, that means that each other may set own filters which will be applied to the documents ONLY for them individually, and other will not be affected. 

The similar functionality is available in Google Spreadsheet, see over here https://support.google.com/docs/answer/9331169?hl=en#6.5

**Comment by rsnegirev** [comment]
Hi @ostasevych 

This is known issue - 50973 in our internal issue tracker.
Thank you for report.

**Comment by cpot** [comment]
Any news for this interesting feature ? @Rita-Bubnova

**Comment by rsnegirev** [comment]
Hi @cpot and @ostasevych 

Perhaps the original question was misinterpreted. Returning to it, I realized that perhaps you were talking about Sheet View Manager:
https://helpcenter.onlyoffice.com/onlyoffice-editors/onlyoffice-spreadsheet-editor/UsageInstructions/SheetView.aspx

Because in this mode you can use your own filters and sorting that do not affect to other users.

Please let me know if I'm wrong.

**Comment by cpot** [comment]
Thank you for your suggestion @rsnegirev , i will share your idea with our customer
