### ISSUE TITLE
Editor version has been updated the page will be reloaded

### ISSUE THREAD

**Issue by systemTetra2** [ONLYOFFICE/DocumentServer#2320]

**Comment by Rita-Bubnova** [comment]
@systemTetra2, Please, fill in all the fields of the form completely.

**Comment by rwyydxy** [comment]
> @systemTetra2, Please, fill in all the fields of the form completely.
I had the same error as him. When I modify the file, the following problems may occur. A prompt box will pop up saying that the version of the file has changed, and the page will be reloaded. Then I cannot modify the file and need to wait. After a period of time, I can access the file normally and edit it normally, but as long as I save the modified content, will this error still occur

**Comment by LuckySpecialist** [comment]
Hi @systemTetra2 & @rwyydxy!
This message is normal behavior when a new version of the file is automatically assembled on the server and you are trying to open the old one.
Your request is very similar to issue #1716.
If your problem is different and you think that the application is working incorrectly, please describe your problem in detail, including the environment.
_I note that we are considering the problem only for the current version of the Document Server (at the moment it is 7.4.1)._

**Comment by aristotekean** [comment]
I'm addressing the same bug, I've deployed onlyoffice document server with docker and conected it to owncloud and S3, in my frontend I use only-office/angular when I edit something from angular or from onlyoffice desktop when I wanna check it from other client I always get "The file version has been changed. The page will be reloaded." from the others clients.
