### ISSUE TITLE
onlyoffice 文档保存后，再打开报“打开文件时出现错误”，后台没有详细错误信息，只有“ExitCode (code=80;signal=null;error:-80)”

### ISSUE THREAD

**Issue by BigXIGuaWang** [ONLYOFFICE/DocumentServer#2414]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Docker

### Version information

7.4.0

### Expected Behavior

保存文档后，正常打开文档

### Actual Behavior

打开保存后的文档出现 “打开文件时出现错误”

### Reproduction Steps

1.打开文档
2.保存文档，显示保存文档成功
3.重新打开文档

### Additional information

后台错误信息
[2023-10-10T02:12:11.265] [ERROR] [localhost] [23F0BDC8B59E4B0245B16B3E71AC7055-1696902337868] [648ffb6520ddd40001290954] nodeJS - stdout:
[2023-10-10T02:12:11.265] [ERROR] [localhost] [23F0BDC8B59E4B0245B16B3E71AC7055-1696902337868] [648ffb6520ddd40001290954] nodeJS - stderr:
[2023-10-10T02:12:11.265] [ERROR] [localhost] [23F0BDC8B59E4B0245B16B3E71AC7055-1696902337868] [648ffb6520ddd40001290954] nodeJS - ExitCode (code=80;signal=null;error:-80)

**Comment by Rita-Bubnova** [comment]
Hello, @BigXIGuaWang. 
Please fill out the form template in english.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.

**Comment by freedomcoming** [comment]
Hello @Rita-Bubnova,


Thank you for your feedback. I apologize for the oversight regarding the form template. I will ensure to complete it in English as requested.


Regarding the issue with OnlyOffice DocumentServer (version 7.4.0) on Docker, where documents save successfully but fail to open with an error message "Error opening file" and an ExitCode of 80, I have not been able to reproduce it with the provided steps. The issue seems unique, and I did not find any similar reports in the search results.


Could you please provide any additional details or logs that might help in diagnosing the problem? Specifically, any error logs from the application or system level that occur when attempting to open the document would be very helpful.


Thank you for your assistance in resolving this matter.


Best regards,

BigXIGuaWang

**Comment by igwyd** [comment]
Hello @freedomcoming , you have a very old version. Try updating to the current 9.2.1 (as today). Your issue may have been fixed. If the issue persists, please open a new one.
