### ISSUE TITLE
Postinstall script problems installing on Ubuntu 18.04

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/DocumentServer#271]
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Try to install documentserver 5.1.0 on Ubuntu 18.04 via [instruction](https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx). 
Step `Adding the repository containing the up-to-date Node.js package versions:` can be ignored, since Ubuntu 18.04 already contained required `nodejs` package in default repo

Result:
On last step, `sudo apt-get install onlyoffice-documentserver` there will be error:
```
dpkg: error processing package onlyoffice-documentserver (--configure):
 installed onlyoffice-documentserver package post-installation script subprocess returned error exit status 127
Errors were encountered while processing:
 onlyoffice-documentserver
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
While trying `bash /var/lib/dpkg/info/onlyoffice-documentserver-ie.postinst` there will be several syntax error.

**Possible solution** 
As found out by @agolybev installing `npm` before install `onlyoffice-documentserver` is enough to fix it

**DocumentServer version:** 5.1.0

**Operating System:** Ubuntu 18.04 Docker image, bionic-20180224

**Comment by barotashish** [comment]
I am getting very similar error after upgrading from Ubuntu-17.10 to Ubuntu-18.04

See the below log messages :- 

ashish@ashish-barot:~$ sudo apt-get upgrade
[sudo] password for ashish: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  curl gnome-keyring gnome-keyring-pkcs11 libcurl3-gnutls libcurl4 libcurl4-openssl-dev libp11-kit-gnome-keyring libpam-gnome-keyring
8 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
373 not fully installed or removed.
Need to get 650 kB/1,530 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://in.archive.ubuntu.com/ubuntu bionic-updates/main amd64 gnome-keyring-pkcs11 amd64 3.28.0.2-1ubuntu1.18.04.1 [26.4 kB]
Get:2 http://in.archive.ubuntu.com/ubuntu bionic-updates/main amd64 gnome-keyring amd64 3.28.0.2-1ubuntu1.18.04.1 [598 kB]
Get:3 http://in.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 libp11-kit-gnome-keyring amd64 3.28.0.2-1ubuntu1.18.04.1 [3,228 B]
Get:4 http://in.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpam-gnome-keyring amd64 3.28.0.2-1ubuntu1.18.04.1 [21.8 kB]
Fetched 650 kB in 2s (384 kB/s)                  
Setting up util-linux (2.31.1-0.4ubuntu3) ...
update-alternatives: error: cannot stat file '/usr/bin/nodejs': Too many levels of symbolic links
dpkg: error processing package util-linux (--configure):
 installed util-linux package post-installation script subprocess returned error exit status 2
dpkg: dependency problems prevent configuration of sysvinit-utils:
 sysvinit-utils depends on util-linux (>> 2.28-2~); however:
  Package util-linux is not configured yet.

dpkg: error processing package sysvinit-utils (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Errors were encountered while processing:
 util-linux
 sysvinit-utils
E: Sub-process /usr/bin/dpkg returned an error code (1)

Can anyone please share any idea for troubleshooting this? 

Thank you in advance. 

Ashish Barot.

**Comment by ShockwaveNN** [comment]
@barotashish I see no mention of `onlyoffice` in your errors. BTW we release 5.1.4 in several weeks and it will compatible with Ubuntu 18.04

**Comment by trenshaw** [comment]
There appears to be a problem with the onlyoffice-documentserver:metrics service not starting through Supervisor on Ubuntu 18.04

util.js:969
    throw new TypeError('The super constructor to "inherits" must not ' +
    ^

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.inherits (util.js:969:11)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/Metrics/node_modules/statsd/lib/config.js:33:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/onlyoffice/documentserver/server/Metrics/node_modules/statsd/stats.js:4:14)

**Comment by ShockwaveNN** [comment]
@trenshaw Seems you already find out solution, but this errors are from if anyone interested https://github.com/ONLYOFFICE/DocumentServer/issues/139

**Comment by ShockwaveNN** [comment]
Just checked this problem with Docker base image `ubuntu:18.04` and `DocumentServer 5.3.0` and seem problem is fixed

**Comment by joskapista44** [comment]
I have an Ubuntu 18.04 server, with an olnyoffice 5.4.1-39. When I try to upgrade it to the next version (5.4.2-46), via APT, I get an error: 

> dpkg: error processing package onlyoffice-documentserver (--configure):
>  installed onlyoffice-documentserver package post-installation script subprocess returned error exit status 1
> Errors were encountered while processing:
>  onlyoffice-documentserver
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> 
When I try to configure it:
> sudo dpkg --configure -a
> [sudo] password for user: 
> Setting up onlyoffice-documentserver (5.4.2-46) ...
> Generating AllFonts.js, please wait...Done
> Generating presentation themes, please wait...Done
> dpkg: error processing package onlyoffice-documentserver (--configure):
>  installed onlyoffice-documentserver package post-installation script subprocess returned error exit status 1
> Errors were encountered while processing:
>  onlyoffice-documentserver

Has anybody any idea what can I do with it? Thanks

(In 2019 spring I had the same problem wiht Onlyoffice and Ubuntu 18.04. I had to disable the repository, and wait till I had time to reinstall everything. It worked. I thought it will solve the problem and maybe next time I will have better luck with it, But it seems the problem is still exist)

**Comment by krz** [comment]
Still got this error on upgrading to 5.6.3-2 on Ubuntu 18.04

**Comment by ShockwaveNN** [comment]
@krz Original error could not be happened, since the reason was nodejs and we do not require nodejs any more
Seems you have some other problem with same dpkg symptom, please create a new issue

**Comment by krz** [comment]
@ShockwaveNN it's kinda hard to describe, actually it's the same what @joskapista44 describes. I had a working onlyoffice install, did a apt update and it's broken with the exact same error @joskapista44 describes.

**Comment by ShockwaveNN** [comment]
@krz See that is the output of `bash /var/lib/dpkg/info/onlyoffice-documentserver.postinst` and create new issue with this info
