### ISSUE TITLE
Mail merge from URL not working if a token is passed in the URL

### ISSUE THREAD

**Issue by raphaelbadawi** [ONLYOFFICE/DocumentServer#2788]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my bug.

### Operating System of DocumentServer

Linux (RPM package)

### Version information

8.1.0.169

### Expected Behavior

When I mail merge (or merge, or compare) a file from a URL, if I use a URL, it works even if a ticket session or a token is passed in the URL.

### Actual Behavior

When I mail merge (or merge, or compare) a file from a URL, if I use a plain URL for a publicly available file, it works. But when I use an URL like mydomain.com/path/to/my/file?ticket=XXXX-XXXX-XX where a ticket session or a token is passed to the URL for authentication to happen, it fails. The link works when pasting it in another browser tab, but OO DocumentServer is not able to download it server side, as if the query params were skipped. I digged a bit into the asc_docs_api.prototype._downloadAs method but didn't find the cause of it.

### Reproduction Steps

1. Get a download link where some hash or token is part of the URL and file is available only if hash or token is valid.
2. Copy it in the "from URL" option of mail merge
3. Apply

**Comment by XDmitryK** [comment]
@raphaelbadawi Hi
Can you attach a screenshot or a short video with docservice or converter logs?

**Comment by adminceovision** [comment]
Of course.

Here I have a document open:
![image](https://github.com/user-attachments/assets/6b03e3cc-6c54-4460-aa11-d55ffb56f0f9)

The document URL has the following format: https://xxx.yyy.com/node/content/XXX?alf_ticket=XXX.

The URL param "alf_ticket" is essential since it contains an access token. So logically, if I copy paste the full URL value in my browser, it downloads the document. 

![Capture d’écran du 2024-08-23 09-23-58](https://github.com/user-attachments/assets/3a2a81bc-1d3a-430b-9ad3-e73eff1bc2a5)

It I remove the access token, it asks for credentials:

![Capture d’écran du 2024-08-23 09-24-17](https://github.com/user-attachments/assets/ac254217-3303-44ec-88e2-4aca88638383)

OO is cohesive with it when I use the URL as the document.url of the instance: it loads the document when I give the full URL in the document.url property, but obviously fails if I remove the URL param from the document.url value. This is what is expected.

But I don't have the same behavior when using such an URL as an URL source for mail merge.

![Capture d’écran du 2024-08-23 09-30-27](https://github.com/user-attachments/assets/33262d33-b09b-4b3a-8571-8f5281720e65)

![Capture d’écran du 2024-08-23 09-30-58](https://github.com/user-attachments/assets/97d17575-2f10-4850-a252-e4232b57aeab)

![Capture d’écran du 2024-08-23 09-31-07](https://github.com/user-attachments/assets/ccf689a5-a0d7-40d9-a6f4-b6eac2dc1f21)

The weirdest part being that I see in my network tab the download request to the URL actually succeeding:

![Capture d’écran du 2024-08-23 09-32-37](https://github.com/user-attachments/assets/4497e4de-adf9-431c-b447-4f8d91306368)

![Capture d’écran du 2024-08-23 09-32-58](https://github.com/user-attachments/assets/2eecad2c-f50f-4d9f-bc3a-0ed0d5384155)

But I still have the error message. When I put the same document in an unprotected URL (no token required, no URL param), it works. So this seems related to the URL having an auth token in an URL param.

**Comment by raphaelbadawi** [comment]
Of course.

Here I have a document open:
![image](https://github.com/user-attachments/assets/6b03e3cc-6c54-4460-aa11-d55ffb56f0f9)

The document URL has the following format: https://xxx.yyy.com/node/content/XXX?alf_ticket=XXX.

The URL param "alf_ticket" is essential since it contains an access token. So logically, if I copy paste the full URL value in my browser, it downloads the document. 

![Capture d’écran du 2024-08-23 09-23-58](https://github.com/user-attachments/assets/3a2a81bc-1d3a-430b-9ad3-e73eff1bc2a5)

It I remove the access token, it asks for credentials:

![Capture d’écran du 2024-08-23 09-24-17](https://github.com/user-attachments/assets/ac254217-3303-44ec-88e2-4aca88638383)

OO is cohesive with it when I use the URL as the document.url of the instance: it loads the document when I give the full URL in the document.url property, but obviously fails if I remove the URL param from the document.url value. This is what is expected.

But I don't have the same behavior when using such an URL as an URL source for mail merge.

![Capture d’écran du 2024-08-23 09-30-27](https://github.com/user-attachments/assets/33262d33-b09b-4b3a-8571-8f5281720e65)

![Capture d’écran du 2024-08-23 09-30-58](https://github.com/user-attachments/assets/97d17575-2f10-4850-a252-e4232b57aeab)

![Capture d’écran du 2024-08-23 09-31-07](https://github.com/user-attachments/assets/ccf689a5-a0d7-40d9-a6f4-b6eac2dc1f21)

The weirdest part being that I see in my network tab the download request to the URL actually succeeding:

![Capture d’écran du 2024-08-23 09-32-37](https://github.com/user-attachments/assets/4497e4de-adf9-431c-b447-4f8d91306368)

![Capture d’écran du 2024-08-23 09-32-58](https://github.com/user-attachments/assets/2eecad2c-f50f-4d9f-bc3a-0ed0d5384155)

But I still have the error message. When I put the same document in an unprotected URL (no token required, no URL param), it works. So this seems related to the URL having an auth token in an URL param.

The only thing I see in the converter log is this:

![image](https://github.com/user-attachments/assets/ee40f888-18b3-4efc-aa76-744ba8481d20)

Hope it will help!

**Comment by XDmitryK** [comment]
@raphaelbadawi 
There are still a few steps left to take:
1.Set  "level": "ALL"  in /etc/onlyoffice/documentserver/log4js/production.json
2.Set  FileConverter.converter.errorfiles:"error" in config file /etc/onlyoffice/documentserver/default.json
3. Restart everything with the command "supervisorctl restart all"

**Comment by XDmitryK** [comment]
Sorry for the late reply. We need to look at the logs in the converter and we need to know which link is used to download
Also, the logs show that there is a conversion error and the original files will be located 
/var/lib/onlyoffice/documentserver/App_Data/cache/files/error/
There you will see what the server downloaded and what it sent for conversion.

**Comment by raphaelbadawi** [comment]
Hmm very weird I retested it this morning with document server 8.1.3 and it successfully got the recipient list from my xlsx file for mail merge, though the link was exactly the kind of link which was problematic before (link with a session token).

I guess some changes made in the meantime collaterally repaired stuff.

**Comment by XDmitryK** [comment]
@raphaelbadawi Sorry for the long reply. No, nothing has changed in the server version at that time, version 8.2 was released on October 17th. If the problem still exists, you can reopen this question.
