### ISSUE TITLE
How to get the edited file stream

### ISSUE THREAD

**Issue by gwmm678** [ONLYOFFICE/DocumentServer#2867]
### This issue is unique.

- [X] I have used the [search tool](https://github.com/ONLYOFFICE/DocumentServer/issues?q=) and did not find an issue describing my idea.

### Your idea.

How to get the edited file stream

**Comment by gwmm678** [comment]
How to get the edited file stream

**Comment by Rita-Bubnova** [comment]
Hello, @gwmm678.
Would you describe in more detail what you need?

**Comment by gwmm678** [comment]
Hello, I have written a plugin that requires the editor to immediately retrieve the edited file stream, extract the desired fields from it, and update them into the plugin

**Comment by gwmm678** [comment]
Hello, @Rita-Bubnova ， I have written a plugin that requires the editor to immediately retrieve the edited file stream, extract the desired fields from it, and update them into the plugin

**Comment by gwmm678** [comment]
@Rita-Bubnova   Hello, I have written a plug-in, and then the editor needs to get the edited file stream immediately after editing, and then extract the fields I want to update to the plug-in

**Comment by askonev** [comment]
@gwmm678 Greetings. Are you reading the stream in the plugin code? This stream contains a document and you want to open it for editing in the editor. Did I understand you correctly?

**Comment by gwmm678** [comment]
@askonev Hello, I want to obtain the file stream of the current document in the plugin. How can I edit the document to obtain the edited file stream

**Comment by askonev** [comment]
@gwmm678 Plugins were originally designed to extend the functionality of the editor using the [Api](https://api.onlyoffice.com/plugin/basic) rather than interacting with the document directly. The very ability to directly access a document from the context of a plugin contradicts the idea of a plugin. Perhaps it makes sense to implement [document server integration ](https://api.onlyoffice.com/editors/basic) for your tasks

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
