### ISSUE TITLE
How can i add Chinese Font and input Chinese?

### ISSUE THREAD

**Issue by xiaolds** [ONLYOFFICE/DocumentServer#38]
I have tried to deploy the Document Server on my Server with docker. and i added some Chinese font on my Server ,but it cannot work normal.

1. When the file name contains Chinese Character, it can not open successful, and there will post a message "Download failed".

![onlyoffice_error2_20160726104141](https://cloud.githubusercontent.com/assets/11567486/17124673/6d077b7e-531f-11e6-9d88-7fa4d24578b8.png)

2. After i added some Chinese Font like songti(宋体),heiti(黑体) on my server, some Character can display normal but other can't, i don't know why.

![onlyoffice_error_20160726104141](https://cloud.githubusercontent.com/assets/11567486/17124849/a522eae2-5320-11e6-9546-1230e8addee9.png)

My server is CentOS7 and the Document Server vision is 4.0.

Thank you~

[out.zip](https://github.com/ONLYOFFICE/DocumentServer/files/382936/out.zip)

**Comment by trofim24** [comment]
Which function to URL encoding you are using ?
As we can see in the out.log space character encoded to `+` instead of `%20`.
[URLEncoder not able to translate space character](http://stackoverflow.com/questions/4737841/urlencoder-not-able-to-translate-space-character)
[When to encode space to plus (+) or %20?](http://stackoverflow.com/questions/2678551/when-to-encode-space-to-plus-or-20)

**Comment by JohnPerkin** [comment]
Dear ONLYOFFICE users!
We are working hard on implementation of asian fonts in Document Server. So we need both standard and non-standard fonts to analyze their behaviour in our product. Please send us fonts via support@onlyoffice.com or attach them to your messages. We will appreciate your assistance.
Best regards
John
ONLYOFFICE support team
