### ISSUE TITLE
Not clear on the differences between Document Server, Community Server, and Mail server

### ISSUE THREAD

**Issue by jcklpe** [ONLYOFFICE/DocumentServer#407]
Messaging for the 3 servers are not clear to me. I can guess that document server is for editing documents and that mail server is for mail, but what is community server for? Does community server include both document and mail server functionalities? Is there any overlap?

If I try to look up "community server features" I can't find the page because google just gives me the features for the "community edition" of OnlyOffice. Is the community edition referring to the specific implementations of the 3 servers or is referring to the app itself? 

All this is very unclear to me. I'm not a full on developer, I'm a UX Designer learning to code, but even so I'm fairly technical and I am having trouble figuring out a straightforward answer to this stuff.

**Comment by ShockwaveNN** [comment]
Hi!
Document Server includes document editors. Just editors for text documents, spreadsheets and presentations. 
Community Server includes collaboration platform (which consists of document management system, projects, CRM, mail aggregator to collect emails from different existing accounts like gmail, and a platform for building corporate social network). So, as you see, it doesn’t include Document and Mail Servers. 
Mail Server includes mail server to send and receive emails using your own domain names.
You may want to use editors ONLY. This means that you need Document Server. However, you can’t use editors without cloud storage. That’s why you need Community Server. It will help you store and manage documents, and also share them with your teammates. 
(OR: you can connect the editors to ownCloud/Nextcloud and use them instead of our Community Server.) 

Document Server + Community Server + Mail Server (optional) = Community Edition (but with the limitation of 20 simultaneous connections to doc editors). Download https://www.onlyoffice.com/download.aspx
Document Server + Community Server + Mail Server (optional) = Enterprise (limitations depend on the tariff plan). Pricing https://www.onlyoffice.com/enterprise-edition.aspx
Thanks for asking. We’ve been working on our products for many years, and it became complicated, we understand this. Please, feel free to ask more questions. We will be glad to help.

**Comment by hellonadya** [comment]
Hi!

**Document Server** includes document editors. Just editors for text documents, spreadsheets and presentations. 

**Community Server** includes collaboration platform (which consists of document management system, projects, CRM, mail aggregator to collect emails from different existing accounts like gmail, and a platform for building corporate social network). So, as you see, it doesn’t include Document and Mail Servers. 

**Mail Server** includes mail server to send and receive emails using your own domain names.

You may want to use editors ONLY. This means that you need Document Server. However, you can’t use editors without cloud storage. That’s why you need Community Server. It will help you store and manage documents, and also share them with your teammates. (OR: you can connect the editors to ownCloud/Nextcloud and use them instead of our Community Server) 

Document Server + Community Server + Mail Server (optional) = **Community Edition** (but with the limitation of 20 simultaneous connections to doc editors). [Download ](https://www.onlyoffice.com/download.aspx)

Document Server + Community Server + Mail Server (optional) = **Enterprise Edition** (limitations depend on the tariff plan). [Pricing](https://www.onlyoffice.com/enterprise-edition.aspx) 

Thanks for asking. We’ve been working on our products for many years, and everything became complicated, we understand this. Please, feel free to ask more questions. We will be glad to help.

**Comment by jcklpe** [comment]
@hellonadya  Thank you! This was a great explanation! Very clear now :) 

One quick follow up question. If I wanted to install the Document Server + Community Server + Mail Server, could I still use the NextCloud integration app with that server? I have a NextCloud personal cloud, and I much much prefer OnlyOffice over Collabora, and would like to use it in my NextCloud personal server instead of Collabora, BUT I also find some of the additional features mentioned in the Community Edition website to be of interest too. Would it be possible to still use the Document/Community/Mail server and also the NextCloud Integration?

And if I was able to use the D/C/M server with the NextCloud Integration app, how many of the Community Server and Mail Server features would be available on my NextCloud personal server through the integration? Would it be possible to use the OnlyOffice CRM or Calendar alongside the NextCloud mail server?

**Comment by CarlOnlyoffice** [comment]
Hello **jcklpe**.

If we talk about ONLYOFFICE integration with Nextcloud, we mean enabling document editing in Nextcloud with ONLYOFFICE Document Editors. You connect the Document Server to your Nextcloud instance by installing a [connector app](https://api.onlyoffice.com/editors/nextcloud). Community and Mail server features cannot be integrated with Nextcloud, only the document editing.

**Comment by jcklpe** [comment]
Thanks!

**Comment by sduensin** [comment]
It's funny this issue is closed and I found it while trying to figure out the same thing - over a year later!  Doesn't "closed" mean you fixed it?  :-)

**Comment by ibnpetr** [comment]
@sduensin We are absolutely ready to add any additional information to this thread. 
Could you please specify the question that still remains unanswered.

**Comment by jcklpe** [comment]
@ibnpetr 
> Could you please specify the question that still remains unanswered.

I think the isue they are speaking about is not about the information in this thread but rather the information on the website. 

Looking over the updated website though the information does seem clearer to me. It helps that you guys have divided the Only Office offerings into Cloud, Enterprise, and Integration. Nice job!

**Comment by sduensin** [comment]
@jcklpe 

Exactly.  I had no idea what the difference between Community Server and Document Server was until I found this thread.  Searching for Community Server tends to bring up the community edition of the software.

**Comment by edvinkuric** [comment]
same here - thanks for the explanation :)

**Comment by Akorian** [comment]
Hi, I am still a little confused. I want to enable local and cloud editing of files stored in my nextcloud server. aka clicking on a file in nextcloud and opening it in the webinterface or in the local only office app. 
From the thread here I think I only need the documentserver image but i am not quite sure...
