### ISSUE TITLE
Can't type "'"

### ISSUE THREAD

**Issue by TooMuchRAM** [ONLYOFFICE/DocumentServer#409]
Hi,
I'd like to report what I think of as a bug.
Whenever I try to type " or ', the character doesn't show up.
Typing characters like 'ü' and 'é' does work.
Additionally, I can't use backspace nor Delete in the presentation editor (don't know about the spreadsheet editor).
Steps to reproduce:
1. Open Presentation Editor
2. Try typing '
3. Type some text
4. Try using backspace

This is quite an annoying issue; I use these keys a lot. I expect these keys to just work.
I don't know if it worked in previous versions of the editor.
Document Server version: 5.2.2-2
Operating System: CentOS 7
Browser version: Firefox 62.0.3

**Comment by ShockwaveNN** [comment]
Please fill issue template correctly https://github.com/ONLYOFFICE/DocumentServer/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by TooMuchRAM** [comment]
I have edited it to reflect your needs.

**Comment by ShockwaveNN** [comment]
@TooMuchRAM sorry we cannot reproduce your issue. What desktop environment do you use? Do you install some custom keyboards? Can you record a video with issue

**Comment by TooMuchRAM** [comment]
I use KDE, with the default keyboard set to English international:
![image](https://user-images.githubusercontent.com/39091235/47155410-f0da1280-d2e4-11e8-9bc2-60bd99acc8f5.png)
I cannot send a video at this time, maybe later.
Using backspace in the document editor does work, and I can normally type ' and " just fine.

**Comment by TooMuchRAM** [comment]
I updated to node v8, and now I am able to use backspace but typing ' and " is still not possible.

**Comment by ShockwaveNN** [comment]
@TooMuchRAM could you try this issue on another client pc?

**Comment by drebs** [comment]
I get the same behaviour, i think it has to do with use of dead keys. Will try to fill template, hope to not be taking over someone else's bug. If that is the case, please let me know and I'll move this to another issue.

**Do you want to request a feature or report a bug?**

Report a bug.

**What is the current behavior?**

When using a keymap with dead keys in Linux, neither `dead_acute` nor `dead_diaresis` (both followed by a space) will show the expected characters.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Open DocumentServer in a Linux environment configured with a keymap that uses dead keys.
2. Try to write a character triggered by dead keys (example: dead grave, dead acute, dead tilde, dead diaresis, dead circumflex), which means type one of those characters followed by a space. 
3. See a space being typed instead of the expected character.

**What is the expected behavior?**

One should see the expected typed dead character (examples: `~`, `"`, `^`, etc).

**Did this work in previous versions of DocumentServer?**

No idea.

**DocumentServer version:**

5.2.2

Operating System:

* Debian Linux 9.5
* Xorg Xserver 1.19.2
* i3 window manager 4.13
* `setxkbmap` for switching between 2 keyboard layouts.

**Browser version:**

Chromium 69.0.3497.92.

**More info**

I give an example of what happens with different keyboard layouts related to the use of apostrpophe.

When I use `setxkbmap -model abnt2 -layout br -variant abnt2`, pressing `'` triggers the following events and **correctly shows an apostrophe in Document Server**:

```
KeyPress event, serial 127, synthetic NO, window 0x4a00001,
    root 0xe0, subw 0x0, time 23862832, (709,-3), root:(712,720),
    state 0x0, keycode 49 (keysym 0x27, apostrophe), same_screen YES,
    XLookupString gives 1 bytes: (27) "'"
    XmbLookupString gives 1 bytes: (27) "'"
    XFilterEvent returns: True

KeyRelease event, serial 127, synthetic NO, window 0x4a00001,
    root 0xe0, subw 0x0, time 23862872, (709,-3), root:(712,720),
    state 0x0, keycode 49 (keysym 0x27, apostrophe), same_screen YES,
    XLookupString gives 1 bytes: (27) "'"
    XFilterEvent returns: False
```

When I use `setxkbmap -model pc104 -layout us -variant intl`, pressing `'` followed by a space triggers the following events and **shows only a space in Document Server and**:

```
KeyPress event, serial 140, synthetic NO, window 0x4a00001,
    root 0xe0, subw 0x0, time 24049820, (894,-2), root:(897,721),
    state 0x0, keycode 0 (keysym 0xb4, acute), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 2 bytes: (c2 b4) "´"
    XFilterEvent returns: False

KeyRelease event, serial 141, synthetic NO, window 0x4a00001,
    root 0xe0, subw 0x0, time 24049883, (894,-2), root:(897,721),
    state 0x0, keycode 48 (keysym 0xfe51, dead_acute), same_screen YES,
    XLookupString gives 2 bytes: (c2 b4) "´"
    XFilterEvent returns: False

MappingNotify event, serial 141, synthetic NO, window 0x0,
    request MappingKeyboard, first_keycode 8, count 248

KeyPress event, serial 141, synthetic NO, window 0x4a00001,
    root 0xe0, subw 0x0, time 24050689, (894,-2), root:(897,721),
    state 0x0, keycode 65 (keysym 0x20, space), same_screen YES,
    XLookupString gives 1 bytes: (20) " "
    XmbLookupString gives 1 bytes: (20) " "
    XFilterEvent returns: False

KeyRelease event, serial 142, synthetic NO, window 0x4a00001,
    root 0xe0, subw 0x0, time 24050753, (894,-2), root:(897,721),
    state 0x0, keycode 65 (keysym 0x20, space), same_screen YES,
    XLookupString gives 1 bytes: (20) " "
    XFilterEvent returns: False
```

**Comment by K0R0L** [comment]
Ok, I will understand.

**Comment by TooMuchRAM** [comment]
Drebs' explanation is much better than mine, it's what I'm facing too.

**Comment by TooMuchRAM** [comment]
I didn't seem to be able to type these dead characters on Windows, too.

**Comment by ShockwaveNN** [comment]
This maybe same issue as DesktopEditors https://github.com/ONLYOFFICE/DesktopEditors/issues/109

**Comment by TooMuchRAM** [comment]
I can indeed confirm that I'm not able to type these characters in the Desktop Editors.

**Comment by DevPre24** [comment]
> This maybe same issue as DesktopEditors [ONLYOFFICE/DesktopEditors#109](https://github.com/ONLYOFFICE/DesktopEditors/issues/109)

Yep, same issue. It doesn't seem to be an OS related problem. I can reproduce it both on Arch Linux (KDE) and Windows 10.

**Comment by TooMuchRAM** [comment]
I've just tried to reproduce the bug in macOS. Possibly due to the way Apple handles typing apostrophes, quotes and special characters (if you type "'", it'll check the character that follows; if it's a character from a predefined list, it'll remove the apostrophe or quote and replace it with the corrosponding character), this bug does not exist in the macOS version.

Details:
macOS 10.14.4 (supposedly) on a ThinkPad T420s
Keyboard set to ANSI, layout is US International PC
Desktop Editors version: 5.2.3 (297)

**Comment by K0R0L** [comment]
Fixed.
https://github.com/ONLYOFFICE/sdkjs/pull/509/commits/3049f81e6aa928ec89ae6c83d4a7f0ce9446cb95

**Comment by ShockwaveNN** [comment]
DocumentServer 5.3.0 is released. This issue has been fixed.
