### ISSUE TITLE
An error has occured while opening the file

### ISSUE THREAD

**Issue by aborderon** [ONLYOFFICE/DocumentServer#421]
Hello,

I am currently having a problem when opening big PPT files.

My file is 25 MB and it can not be opened, I get the following error message:
![image](https://user-images.githubusercontent.com/6728728/48050041-02566200-e1a1-11e8-8177-276adf836cff.png)

It works very well with small files.

I also have no error message in the logs ...

I saw that there were similar problems in other issues but with no solution.

Do you have any idea of ​​my mistake?

Thank you

**DocumentServer version:**
5.2.2 CE

**Comment by ShockwaveNN** [comment]
@aborderon could you attach this file?

**Comment by aborderon** [comment]
@ShockwaveNN I just put the file at your disposal.
https://ufile.io/nvdd9

**Comment by Rita-Bubnova** [comment]
@aborderon the problem is that your decompressed PPTX file is about 72MB. This is more than the specified limit (50MB).

We have corrected the error message to be more informative (see screenshot).

![Issue 421](https://user-images.githubusercontent.com/25282241/88392628-f96a5180-cdc4-11ea-9e84-e2547368caa7.png)

If you want to change the limit, you need to open `/etc/onlyoffice/documentserver/default.json`. In the `FileConverter` section you will find "uncompressed" which needs to be changed:

{
        "type": "pptx;ppsx;potx;pptm;ppsm;potm",
        "zip": {
          "uncompressed": "50MB",
          "template": "*.xml"
        }
        }

But there was an error when opening your PPTX file, we fixed it (https://github.com/ONLYOFFICE/sdkjs/commit/0e7aa2ed42cdbfa8e5ac0787d160df51f7317497) in next release.

If you increase the limit (in next release Document Server), your PPTX file will open (see screenshot).

![Issue 421 (2)](https://user-images.githubusercontent.com/25282241/88392606-f3747080-cdc4-11ea-9c31-e5150ab4b8a8.png)
