### ISSUE TITLE
/lib64/libcurl-gnutls.so.4: no version information available (required by /lib64/libkernel.so)

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/DocumentServer#434]
**What is the current behavior?**
1. Install DocumentServer on latest centos 7 using
https://helpcenter.onlyoffice.com/server/linux/document/linux-installation-centos.aspx
2. On `sudo yum install onlyoffice-documentserver` step there will be error in install log:
```
Installing : onlyoffice-documentserver-ie-5.2.3-64.x86_64                                                                                 75/75 
Generating AllFonts.js, please wait.../var/www/onlyoffice/documentserver/server/tools/AllFontsGen: /lib64/libcurl-gnutls.so.4: no version information available (required by /lib64/libkernel.so)
Done
warning: %post(onlyoffice-documentserver-ie-5.2.3-64.x86_64) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package onlyoffice-documentserver-ie-5.2.3-64.x86_64
```

**DocumentServer version:** 5.2.3.64

**Operating System:** 
DigitalOcean Centos Image with latest updates
```
# cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core)
```

**Browser version:** Not related

**Comment by ShockwaveNN** [comment]
Issue from https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/228

**Comment by arlindbushi** [comment]
Logs: 
2018/11/21 08:01:20 [error] 2142#2142: *171 open() "/var/www/onlyoffice/documentserver/sdkjs/common/AllFonts.js" failed (2: No such file or directory), client: 79.106.161.144, server: , request: "GET /v5.2.3-64//sdkjs/common/AllFonts.js HTTP/1.1", host: "bt1.develop.al", referrer: "https://bt1.develop.al/v5.2.3-64//web-apps/apps/documenteditor/main/index.html?_dc=5.2.3-64&lang=en-GB&customer=ONLYOFFICE&frameEditorId=iframeEditor"

I think that the problem is in generating AllFonts.JS - I try to execute it manually the bash script of fonts (bash /usr/bin/documentserver-generate-allfonts.sh), but no success. I have this error:

Generating AllFonts.js, please wait.../var/www/onlyoffice/documentserver/server/tools/AllFontsGen: /lib64/libcurl-gnutls.so.4: no version information available (required by /lib64/libkernel.so) 
/usr/bin/documentserver-generate-allfonts.sh: line 21: 29172 Killed

**Comment by noraj** [comment]
duplicate of #146, #6, etc.

**Comment by nneo16** [comment]
try these command:
yum install libcurl    
yum install libcurl-devel

**Comment by ShockwaveNN** [comment]
Seems this problem is not actual any more. Don't know when it was fixed, but there is no warining installing DocumentServer v6.3.2.2 on Centos 7
