### ISSUE TITLE
Security problem - Cached Files

### ISSUE THREAD

**Issue by ExaconAT** [ONLYOFFICE/DocumentServer#449]
**Problem:** 

- Upload, create Office file in Nextcloud: close it.
- Data still remains @ /var/lib/onlyoffice/documentserver/App_Data/cache/files

Is it possible to automatically remove this files?

Already changed the Config in /etc/onlyoffice/documentserver/default.json
for filesCron and documentsCron to 1 hour, but the files wont get wiped.

**Best practice would be: Delete the files after all Users closed the Document.**

**Comment by hahaxd35** [comment]
I dont know why but the garbage collector dont work on default setting... after change  to lower values this work now but older files still remain

**Comment by falling-star** [comment]
Specific to view mode of OnlyOffice, Are cached files deleted by cron job once view mode has loaded? or they are deleted when view mode session is closed? Ideally once the view mode has loaded, files should get deleted.

**Comment by ShockwaveNN** [comment]
@falling-star There is no difference for cron job between view and edit mode
Files are deleted by cron job if there is no user in it

We got that idea in mind, to allow delete cached file, but currently we need to change a lot of code and we cannot guarantee time frame when this feature will be implemented

**Comment by summersab** [comment]
So, I edited the source and configured garbage collection to run immediately when `closeDocument()` is executed. I basically just duplicated the existing functions in `gc.js` and modified them to accept a document ID. When the document is closed, garbage collection runs and cleans up the cache if the document is not open by another participant. It's pretty straightforward.

I'd be happy to submit a PR, but I have a few questions, first. In my opinion, this is an either/or scenario - either automatic garbage collection can be enabled or the server will use the existing cron system. With automatic garbage collection enabled, there is no need for the cron scheduler to run since closing the document cleans up cached files immediately. I can edit my code to make this an optional feature that can be enabled via `local.json`. Thoughts?

On a related topic, if the cache files are manually deleted without running garbage collection, OnlyOffice can no longer open the related files, they appear to be corrupted, and an error message is thrown. What causes this? Is the file still locked somewhere? Is there a way to manually recover the file and reset the locks? I'm still tracing the code, but any pointers would be helpful.

**Comment by ShockwaveNN** [comment]
@summersab I definitely do not answers to any of this question

But maybe @konovalovsergey may help if he got free time
