### ISSUE TITLE
Black font with Bold problem

### ISSUE THREAD

**Issue by kevindenight** [ONLYOFFICE/DocumentServer#544]
**Do you want to request a *feature* or report a *bug*?**
I just want to know why implements this feature.
**What is the current behavior?**
In an excel file, choose a "Black" font and active "Bold", the text will be covered up by the cell border.

Black font without Bold:
![image](https://user-images.githubusercontent.com/8637962/56016024-92d73680-5d2d-11e9-9448-f0ea511ee805.png)
Black font with Bold:
![image](https://user-images.githubusercontent.com/8637962/56016051-a71b3380-5d2d-11e9-97bc-a491d835ccf2.png)

I searched the source code, and found a variable "IsAdvanceNeedBoldFonts", it controls whether increasing the distance by 1 pixel wide in cell mode.
Why we need this?

**Comment by Rita-Bubnova** [comment]
Hello, @kevindenight.
Can you attach a file that repeats the problem?

**Comment by kevindenight** [comment]
Here：[onlyoffice.xlsx](https://github.com/ONLYOFFICE/DocumentServer/files/3072238/onlyoffice.xlsx)

**Comment by K0R0L** [comment]
This flag is responsible for whether to increase the width of the character in the fonts in which we make bold (bold style not presented). For extra-bold fonts - this is not necessary. In this bug. He's fixed. [Thanks.](https://github.com/ONLYOFFICE/sdkjs/commit/5729b83b0360db80fc24a52650e7a0c77e5cba71) A IsAdvanceNeedBoldFonts is needed, since the Word and Excel are behaving differently (every non extra-bold font without natve bold style)
