### ISSUE TITLE
HiDPI support for document body?

### ISSUE THREAD

**Issue by dongwoo21** [ONLYOFFICE/DocumentServer#711]
Hello. I'm a big fan of onlyoffice integration with nextcloud.

Thanks for your hard work first.

I don't know whether this is the problem of onlyoffice document server or the integration,

but the thing is my documents look blurry in onlyoffice.

I'm using 2560x1440 resolution monitor with 125% scale and firefox as a client.

When getting into the onlyoffice through nextcloud, it shows me a blurry text:

![firefox](https://user-images.githubusercontent.com/17664107/70017537-b99cf280-15c6-11ea-952b-5257891ab19f.png)

You may see the difference between texts in layout header and body (+ row, column numbers).

I tested the same thing in chrome, and the result was the same.

Is it normal? or Are there any ways to solve the problem?

**Comment by Rita-Bubnova** [comment]
Hello, @lovestat.
This is a known issue, we are working to fix it.

**Comment by p-baum** [comment]
I'm also very annoyed by blurry document text on linux. Menus are fine however.

**Comment by vouape** [comment]
The same here using linux.

**Comment by vouape** [comment]
Actually I got it looking sharp only with the firefox zoom at 133%.

**Comment by morbificagent** [comment]
Any news about this?

**Comment by awsms** [comment]
> Any news about this?

**Comment by LuckySpecialist** [comment]
Hi to all!
Support for high-resolution monitors is currently available.
There are problems with intermediate scales under Firefox (read [here](https://github.com/ONLYOFFICE/DocumentServer/issues/765#issuecomment-1216263439)). If your problem is related to them, you will have to wait for a [fix](https://github.com/ONLYOFFICE/DocumentServer/issues/765#issuecomment-1724482246) or use the scales supported by our application. In this case, this problem is a duplicate #765.

**Comment by Rita-Bubnova** [comment]
So I close this issue. Feel free to comment or reopen it if you got further questions.
