### ISSUE TITLE
Bulletpoints messed up in libreoffice created OOXML

### ISSUE THREAD

**Issue by y0va** [ONLYOFFICE/DocumentServer#718]
**Do you want to request a *feature* or report a *bug*?**
**bug**

**What is the current behavior?**
Bulletpointlists created in libreoffice and saved as docx are displayed with random *non-bullet* symbols in OnlyOffice.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a file in libreoffice and open it with OnlyOffice Documentserver in Nextcloud.

**What is the expected behavior?**
Fluent import/export

**Did this work in previous versions of DocumentServer?**
No.

**DocumentServer version:**
5.4.2

**LibreOffice Version**
6.3.4.2

**Browser version:**
Firefox 71.0

Example file: [bullets.docx](https://github.com/ONLYOFFICE/DocumentServer/files/3964291/bullets.docx)

related to: #702

**Comment by Rita-Bubnova** [comment]
Hello, @y0va.
Could you attach ODT file created in LibreOffice?

**Comment by y0va** [comment]
If the file is first saved as docx, then edited with onlyoffice and the saved with libreoffice as odt, the strange symbols persist. 

Working with odt on both ends seems to work for simple lists, but I had similar problems with more complicated formatting. 

Find the odt here: https://cloud.solawi.allmende.io/s/nPBzTksXSJEssRf

**Comment by Rita-Bubnova** [comment]
Unfortunately, while I can not reproduce your problem.
Can you describe separately each step in producing the problem and attach the files that are obtained after each save and screenshot bullets?

**Comment by Rita-Bubnova** [comment]
It seems that the problem is with the fonts you have installed.
I open your ODT file on different computers in LibreOffice and get different results:

![image_2019-12-17_16-15-56](https://user-images.githubusercontent.com/25282241/70998613-c7836500-20e8-11ea-8e9f-20214f74f82f.png)
screenshot 1 - Windows 10, LibreOffice 6.3.4.2,

![image](https://user-images.githubusercontent.com/25282241/70998654-dcf88f00-20e8-11ea-9b29-5c715c56fd8f.png)
screenshot 2 - Kubuntu 18.04, LibreOffice 6.3.3.2.

Please, attach a screenshot of the window "Special Characters" so that we understand what symbol you expect to see in the bullet list.

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
