### ISSUE TITLE
If the text is bold when printing, the printed version will be much thicker than the page display font

### ISSUE THREAD

**Issue by nobt854** [ONLYOFFICE/DocumentServer#827]
**Do you want to request a *feature* or report a *bug*?**
1. feature
2. bug
**What is the current behavior?**

1. onlyoffice does not support document grids. Does this feature support it later?
2. If the text is bold when printing, the printed version will be much thicker than the page display font

**DocumentServer version:**
5.4.2
**Operating System:**
Win10
**Browser version:**
Chrome 79.0.3945.130

**Comment by Rita-Bubnova** [comment]
I reproduced the problem using the "DCHBasisschrift" font.
This problem is related to our method of displaying font without Bold in font file, but Bold was applied to them.
We hope to resolve this problem in future and I created a new issue 45587 in our private issue track. But currently it's not high priority issue for us.

**Comment by bigbencat** [comment]
![7AA2EBF7-EB5B-48BF-AD30-CF30A0699FB7](https://user-images.githubusercontent.com/9876006/101755141-806b5c80-3b0f-11eb-8a93-00643d95ca00.png)
the same bug ~

**Comment by bigbencat** [comment]
![1607594115323](https://user-images.githubusercontent.com/9876006/101756430-f91ee880-3b10-11eb-99ea-59f8fb7af094.jpg)
Chinese is more serious, please solve it as soon as possible, thank you

**Comment by bigbencat** [comment]
Chinese is more serious, please solve it as soon as possible, thank you

**Comment by trofim24** [comment]
We've fixed this problem in version 6.4
