### ISSUE TITLE
Document server not working behind AWS elastic load balancer with https

### ISSUE THREAD

**Issue by naveenkumara** [ONLYOFFICE/DocumentServer#89]
Hi, 
     We are trying to setup docker version of onlyoffice document server behind AWS elastic loadbalancer.  Editor opens and gives a pop Unknown error and stops.
Chrome Network console shows (blocked:mixed-content) error, because the parent page is https.

http://onlyoffice.example.com/cache/files/PuPG3IVSWZ/Editor.bin/Editor.bin?md5=blrK40H0D_reJ8wzFBZ2sg==&expires=1490791007&disposition=attachment&ooname=output.bin

![onlyoffice](https://cloud.githubusercontent.com/assets/19905399/24199530/edfabef4-0f2f-11e7-98c9-0c02a90b41d5.PNG)

AWS Elastic load balancer is forwording X-forward-proto and other headers.

**Comment by agolybev** [comment]
Hi.
How did you configure SSL, by the AWS Load Balancer or by the ONLYOFFICE DocumentServer docker container?

**Comment by naveenkumara** [comment]
AWS load balancer is listening to https and onlyoffice is listening to http

**Comment by agolybev** [comment]
Hi
I just checked the described issue. It works for me:
First, I run EC2 instance with ONLYOFFICE DocumentServer in docker.  Then I run EC2 Classic Load Balancer with HTTPS->HTTP rule and connect it with DocumentServer instance. Any problem wasn't detected.
Can you provide browser network log when issue happend?

Additionally, I would not recommend using the EC2 Load Balalncer with ONLYOFFICE  DocumentServer, because the EC2 Load Balalncer does not support websocket traffic. When a websocket is not available, the DocumentServer will use less productive protocols to connect with users, it could work less responsive and more resource-intensive.
If you want to use DocumentServer in this case, for correct work you should enable load balancer generated cookie stickiness.

**Comment by agolybev** [comment]
The issue can not be reproduced.
