### ISSUE TITLE
The content controls function customize.

### ISSUE THREAD

**Issue by yoyomule** [ONLYOFFICE/DocumentServer#907]
request a *feature*

Hello, I see that onlyoffice can realize the content controls function(https://www.youtube.com/watch?v=ic0Q2a4Ae2k), my question is:
1. Is it possible to customize the controls?
2. Whether to connect the control with the database to realize the form filling function.
Thanks

**Comment by ShockwaveNN** [comment]
@flaminestone Please, take a look

**Comment by flaminestone** [comment]
Hello @yoyomule. 
1) Customizing content controls is possible only from settings of content controls.
2) You can use most of abilities of javascript in brouser in plugins, and if you need to connect to database from editors - you can use this way. But it is not good practic because it is not securely. A better way to connect to a database would be to use some server side programm language

**Comment by yoyomule** [comment]
Thank you. Are there any examples of custom controls and forms connected through the server api interface?

**Comment by flaminestone** [comment]
See this https://github.com/ONLYOFFICE/sdkjs-plugins/tree/master/examples/example_work_with_content_controls
It is example how to add content controls, and add data to it via plugins. In this repo you can find other examples too.

You need to write server api interface by youself, and use js in plugin for using it. Plugin [translate](https://github.com/ONLYOFFICE/sdkjs-plugins/tree/master/translate) is used server api interface for taking data for translate text, may be it help you

About customizing content controls - I found one old example for using it, but it is not documented feature
https://github.com/ONLYOFFICE/sdkjs-plugins/tree/master/examples/example_customfields_add

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
