### ISSUE TITLE
Keep chat history

### ISSUE THREAD

**Issue by ydelattre** [ONLYOFFICE/DocumentServer#912]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
history chat are reset when there is no more users on the document
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
not a bug
**What is the expected behavior?**
keep the chat history until the document is deleted
**Did this work in previous versions of DocumentServer?**
no
**DocumentServer version:**
5.5.1
**Operating System:**
Windows 10
**Browser version:**
 Firefox 77.0.1 64 bits

**Comment by ShockwaveNN** [comment]
Hi, we already has a discussion about saving chat in document (issue #30659 in our private issue tracker), but currently we do not planning to implement it because it's not an easy task to implement without losing compatibility with MS Office

I'll leave this issue opened, but I don't think we'll implement it in near future

**Comment by ydelattre** [comment]
Hello,
i understand. 
Thanks for your quick answer !

**Comment by ShockwaveNN** [comment]
I'll close this issue since we are still not planning to implement saving it, but feel free to comment here if this feature really needed
